openapi: 3.0.0
info:
  title: Financial Advisor Backend API
  description: Backend service for the financial advisor frontend.
  version: "1.0"
servers:
  - url: http://localhost:8084
    description: Development server
paths:
  /common/kyc:
    post:
      summary: Fetch KYC details
      description: Retrieves the KYC data.
      operationId: kyc
      parameters:
        - name: authorization
          in: header
          required: true
          description: Bearer token for authorization.
          schema:
            type: string
            example: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIs..."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - kycIdentityType
                - IdentityNumber
              properties:
                kycIdentityType:
                  type: string
                  description: Type of the identity used for KYC (A - Aadhaar / P - PAN).
                  example: "A"
                IdentityNumber:
                  type: string
                  description: Identity number associated with the selected type.
                  example: "3243132568798"
      responses:
        "200":
          description: KYC data fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: HTTP status code
                    example: 200
                  message:
                    type: string
                    description: Status message
                    example: "KYC data fetched successfully"
                  data:
                    type: object
                    properties:
                      aadhaar:
                        type: object
                        description: Aadhaar details
                        properties:
                          aadhaar_number:
                            type: string
                            description: Masked Aadhaar number
                            example: "XXXX-XXXX-1234"
                          aadhaar_status:
                            type: string
                            description: Status of Aadhaar verification
                            example: "Verified"
                          aadhaar_holder_name:
                            type: string
                            description: Name of the Aadhaar holder
                            example: "Ravi Kumar"
                          aadhaar_verification_date:
                            type: string
                            description: Aadhaar verification date
                            example: "2024-12-01"
                          aadhaar_expiry_date:
                            type: string
                            description: Aadhaar expiry date
                            example: "2034-12-01"
                          aadhaar_issue_authority:
                            type: string
                            description: Issuing authority of Aadhaar
                            example: "UIDAI"
                          aadhaar_consent_status:
                            type: string
                            description: Consent status for Aadhaar data sharing
                            example: "Granted"
                          aadhaar_status_message:
                            type: string
                            description: Status message for Aadhaar verification
                            example: "Aadhaar is verified and active."
                      pan:
                        type: object
                        description: PAN details
                        properties:
                          pan_number:
                            type: string
                            description: Masked PAN number
                            example: "ABCDE****F"
                          pan_status:
                            type: string
                            description: Status of PAN verification
                            example: "Active"
                          pan_holder_name:
                            type: string
                            description: Name of the PAN holder
                            example: "Ravi Kumar"
                          pan_verification_date:
                            type: string
                            description: PAN verification date
                            example: "2024-11-25"
                          pan_expiry_date:
                            type: string
                            description: PAN expiry date
                            example: "2030-11-25"
                          pan_issue_authority:
                            type: string
                            description: Issuing authority of PAN
                            example: "Income Tax Department"
                          pan_consent_status:
                            type: string
                            description: Consent status for PAN data sharing
                            example: "Granted"
                          pan_status_message:
                            type: string
                            description: Status message for PAN verification
                            example: "PAN is active and linked to tax records."
        "401":
          description: Unauthorized - Invalid token
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Unauthorized access."

  /common/verify-kyc:
    post:
      summary: Check otp and Fetch KYC details
      description: Retrieves the KYC data after varifying otp.
      operationId: verifyKyc
      parameters:
        - name: authorization
          in: header
          required: true
          description: Bearer token for authorization.
          schema:
            type: string
            example: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIs..."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - otp
              properties:
                otp:
                  type: string
                  description: OTP to verify.
                  example: "123456"
      responses:
        "200":
          description: Otp verified successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: HTTP status code
                    example: 200
                  message:
                    type: string
                    description: Status message
                    example: "Otp verified successfully"
                  data:
                    type: object
                    properties:
                      aadhaar:
                        type: object
                        description: Aadhaar details
                        properties:
                          aadhaar_number:
                            type: string
                            description: Masked Aadhaar number
                            example: "XXXX-XXXX-1234"
                          aadhaar_status:
                            type: string
                            description: Status of Aadhaar verification
                            example: "Verified"
                          aadhaar_holder_name:
                            type: string
                            description: Name of the Aadhaar holder
                            example: "Ravi Kumar"
                          aadhaar_verification_date:
                            type: string
                            description: Aadhaar verification date
                            example: "2024-12-01"
                          aadhaar_expiry_date:
                            type: string
                            description: Aadhaar expiry date
                            example: "2034-12-01"
                          aadhaar_issue_authority:
                            type: string
                            description: Issuing authority of Aadhaar
                            example: "UIDAI"
                          aadhaar_consent_status:
                            type: string
                            description: Consent status for Aadhaar data sharing
                            example: "Granted"
                          aadhaar_status_message:
                            type: string
                            description: Status message for Aadhaar verification
                            example: "Aadhaar is verified and active."
                      pan:
                        type: object
                        description: PAN details
                        properties:
                          pan_number:
                            type: string
                            description: Masked PAN number
                            example: "ABCDE****F"
                          pan_status:
                            type: string
                            description: Status of PAN verification
                            example: "Active"
                          pan_holder_name:
                            type: string
                            description: Name of the PAN holder
                            example: "Ravi Kumar"
                          pan_verification_date:
                            type: string
                            description: PAN verification date
                            example: "2024-11-25"
                          pan_expiry_date:
                            type: string
                            description: PAN expiry date
                            example: "2030-11-25"
                          pan_issue_authority:
                            type: string
                            description: Issuing authority of PAN
                            example: "Income Tax Department"
                          pan_consent_status:
                            type: string
                            description: Consent status for PAN data sharing
                            example: "Granted"
                          pan_status_message:
                            type: string
                            description: Status message for PAN verification
                            example: "PAN is active and linked to tax records."
        "401":
          description: Unauthorized - Invalid token
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Unauthorized access."
